import os
import browser_cookie3


try:
    # 默认与 youtube_downloader.py 保持一致；可通过环境变量覆盖
    output_path = os.getenv("YTDLP_COOKIES_PATH", "youtube_cookies.txt")

    # 尝试读取 Chrome cookies（也可改成 browser_cookie3.load() 自动探测）
    cj = browser_cookie3.chrome()

    # 导出为 Netscape 格式（yt-dlp 可直接使用）
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("# Netscape HTTP Cookie File\n")
        f.write("# https://curl.se/docs/http-cookies.html\n")
        f.write("# This file was generated by a script.\n\n")

        for cookie in cj:
            if "youtube.com" in cookie.domain or "google.com" in cookie.domain:
                f.write(
                    f"{cookie.domain}\t"
                    f"{'TRUE' if cookie.domain.startswith('.') else 'FALSE'}\t"
                    f"{cookie.path}\t"
                    f"{'TRUE' if cookie.secure else 'FALSE'}\t"
                    f"{cookie.expires if cookie.expires else 0}\t"
                    f"{cookie.name}\t"
                    f"{cookie.value}\n"
                )

    print(f"YouTube cookies exported to {output_path}")

except Exception as e:
    print(f"Error exporting cookies: {e}")
    print("Make sure your browser is closed and try again.")
